// Completa CLIENT_ID después de registrar la app en Azure AD (ver instrucciones).
const CONFIG = {
  CLIENT_ID: "6df28c63-6c7e-4c74-a87f-af63e9fe3d0f",
  AUTHORITY: "https://login.microsoftonline.com/common",
  REDIRECT_URI: window.location.origin + window.location.pathname,
  GRAPH_SCOPES: ["Files.ReadWrite", "User.Read"],
  EXCEL_FILENAME: "BASE_DE_DATOS_v2.xlsx",
  RUTA_ARCHIVO: "Documents/BASE_DE_DATOS_v2.xlsx",
  TABLE_NAME: "TablaBaseDatos",
  TABLA_PRODUCTOS_APLICADOS: "Productos_Aplicados",
  TABLA_PRODUCTOS_RECOMENDADOS: "Productos_Recomendados",
  TABLA_PRODUCTIVIDAD: "Productividad_Fincas",
  TABLA_OBSERVACIONES_LOTES: "Observaciones_Lotes",
  TABLA_INFORMES_GENERADOS: "Informes_Generados",
  TABLA_PRODUCTOS: "Tabla2",
  HOJA_CONFIG: "Configuracion",
  HOJA_CLIENTES: "Clientes_Fincas",
  HOJA_PRODUCTOS: "Productos",
  ASESOR: {
    nombre: "Miguel Leon",
    telefono: "3229636167",
    profesion: "Ingeniero Agrónomo",
    cargo: "Asesor Técnico Comercial - Galagro Norte de Antioquia",
  },
};
